### ISSUE TITLE
.method must be one of "entry-global", "usage-global" or "usage-pure" (received "usage-entry")

### ISSUE THREAD

**Issue by pustovalov** [babel/babel-polyfills#20]
According to the migration guide:
https://github.com/babel/babel-polyfills/blob/master/docs/migration.md#core-js3

added:
```
      [
        'polyfill-corejs3',
        {
          method: "usage-entry",
        }
      ],
```

and got this an error:
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
 
Error: [BABEL] /home/circleci/project/app/javascript/packs/lite/lite.js: .method must be one of "entry-global", "usage-global" or "usage-pure" (received "usage-entry") (While processing: "/home/circleci/project/node_modules/babel-plugin-polyfill-corejs3/lib/index.js")
 
    at resolveOptions (/home/circleci/project/node_modules/@babel/helper-define-polyfill-provider/lib/index.js:44:11)
 
    at instantiateProvider (/home/circleci/project/node_modules/@babel/helper-define-polyfill-provider/lib/index.js:77:7)
 
    at /home/circleci/project/node_modules/@babel/helper-define-polyfill-provider/lib/index.js:187:9
 
    at /home/circleci/project/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
 
    at /home/circleci/project/node_modules/@babel/core/lib/config/full.js:199:14
 
```

didn't find any mention of `usage-entry` in the code for `babel-plugin-polyfill-corejs3`

**Comment by nicolo-ribaudo** [comment]
Oh thanks! I fixed the docs.

**Comment by pustovalov** [comment]
Thx, maybe also need to remove or update this section:

https://github.com/babel/babel-polyfills/blob/master/docs/usage.md#method

**Comment by nicolo-ribaudo** [comment]
Thanks :+1:
